import './globals.scss'
import Context from './comp/Context'
import { Inter } from 'next/font/google'
import Footer from './comp/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" type="image/png" sizes="16x16" href='/icons/windows11/Square44x44Logo.targetsize-16.png' />
      </head>
      <body >
        <Context>
          <header></header>
          <main>
            {children}
          </main>
          <footer>
          <Footer/>
          </footer>
        </Context>
      </body>
    </html>
  )
}
